// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  book_appointment: dynamic(() => import("./BookAppointment")),
  card: dynamic(() => import("./WideCard")),
  contact_form: dynamic(() => import("./ContactForm")),
  employee_listing: dynamic(() => import("./EmployeeListing")),
  hero: dynamic(() => import("./Hero")),
  hero_home: dynamic(() => import("./HeroHome")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  quick_links: dynamic(() => import("./QuickLinks")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  treatment_list: dynamic(() => import("./TreatmentList")),
};
